"""ingredients table

Revision ID: 68220aed94eb
Revises: 42f50ef18ccb
Create Date: 2024-11-03 16:35:43.280967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68220aed94eb'
down_revision = '42f50ef18ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ingredient_recipe_id'))

    op.drop_table('ingredient')
    # ### end Alembic commands ###
